export const chineseZodiacAnimals = [
  'Rat',
  'Ox',
  'Tiger',
  'Rabbit',
  'Dragon',
  'Snake',
  'Horse',
  'Goat',
  'Monkey',
  'Rooster',
  'Dog',
  'Pig',
];

const zodiacDetails: Record<string, { emoji: string; tone: string; dailyInsights: string[] }> = {
  Rat: {
    emoji: '🐭',
    tone: 'Clever, quick, full of charm',
    dailyInsights: [
      'Your instincts are faster than your logic today. Act on them.',
      'Someone nearby needs your quick thinking. Show up.',
      'Information you gather today is worth more than you expect.',
      'Your charm is your most powerful tool this morning. Use it.',
      'Stay light on your feet — the best move today requires agility.',
      'A small observation others missed is your biggest advantage today.',
      'Adaptability is your superpower. Embrace the change coming your way.',
      'Your resourcefulness can solve what no one else has figured out yet.',
      'Connections you make today carry long-term value. Be open.',
      'Quick decisions made with good intentions rarely go wrong for you.',
    ],
  },
  Ox: {
    emoji: '🐮',
    tone: 'Steady, patient, deeply grounded',
    dailyInsights: [
      'Your patience today will accomplish more than speed ever could.',
      'Do not underestimate the quiet power of your focus.',
      'Finish what you started. Completion is your superpower.',
      'The steady path is the right one today. Do not be rushed.',
      'Your reliability is your greatest asset. Let it speak for you.',
      'Hard work placed quietly today compounds into something visible soon.',
      'Slow and deliberate beats fast and careless every single time.',
      'Your endurance is what others admire most. Keep going.',
      'A promise kept today strengthens something important in your life.',
      'Ground yourself before the day begins — your clarity is an advantage.',
    ],
  },
  Tiger: {
    emoji: '🐯',
    tone: 'Brave, bold, radiant spirit',
    dailyInsights: [
      'Your boldness is a gift today. Do not dilute it.',
      'Lead from the front. Others are watching for your signal.',
      'The thing you are afraid to do is exactly the right next move.',
      'Your fire energy attracts the right attention today — use it well.',
      'Take the risk. The Tiger\'s spirit is fully with you.',
      'Courage is not the absence of fear — it is acting despite it. Go.',
      'Your intensity today inspires people who needed to see it.',
      'A direct conversation you have been avoiding will go better than expected.',
      'Trust the roar inside you. It knows the direction before you do.',
      'Today your energy sets the tone for the room. Set it well.',
    ],
  },
  Rabbit: {
    emoji: '🐰',
    tone: 'Gentle, graceful, softly luminous',
    dailyInsights: [
      'Your intuition is more accurate than any plan today.',
      'Move gently and you will go further than force allows.',
      'The quiet room holds the best opportunity for you today.',
      'Your sensitivity is a strength, not a weakness. Trust it.',
      'Good things come to those who move with grace and intention.',
      'Peace of mind is your greatest resource. Guard it carefully today.',
      'The most elegant solution is often the simplest one. Look for it.',
      'Diplomacy in a tense moment today opens a door that force would close.',
      'You notice what others rush past. That noticing is your edge.',
      'Your soft influence reaches further than loud demands ever could.',
    ],
  },
  Dragon: {
    emoji: '🐲',
    tone: 'Magnetic, powerful, golden energy',
    dailyInsights: [
      'Your presence commands the room today. Be conscious of your impact.',
      'Ambition meets fortune in your energy right now.',
      'You carry more power than you realize. Own it without apology.',
      'The bold move you have been considering — today supports it.',
      'Your magnetic energy draws the right people closer today.',
      'Vision without action is a dream. Take one step toward yours today.',
      'Fortune favors the Dragon who acts with confidence and clarity.',
      'The door you push on today was waiting for exactly your strength.',
      'Your optimism is not naive — it is a force that bends outcomes.',
      'Big energy requires big intention. Set it early and hold it all day.',
    ],
  },
  Snake: {
    emoji: '🐍',
    tone: 'Wise, intuitive, quietly powerful',
    dailyInsights: [
      'Observe before you act. Your wisdom sees what others miss.',
      'Say less and notice more. Your power today is in watching.',
      'Trust the long game. You are further ahead than it feels.',
      'Your strategic mind gives you an edge no one else in the room has.',
      'A slow, calculated move today beats a fast, impulsive one.',
      'The answer you seek is already inside you. Sit quietly and listen.',
      'Mystery is your asset — do not reveal everything at once.',
      'Your deepest instinct today is also your most accurate compass.',
      'Patience in negotiation today yields far more than urgency would.',
      'Something you perceive as a setback is actually a redirect to better.',
    ],
  },
  Horse: {
    emoji: '🐴',
    tone: 'Free-spirited, bright, always moving',
    dailyInsights: [
      'Move toward what excites you. Your energy follows momentum.',
      'Follow the path that feels most alive to you today.',
      'Your best luck comes through movement — literal or figurative.',
      'Freedom is your fuel. Protect your independence and time today.',
      'Say yes to the invitation that makes your spirit lift.',
      'Your enthusiasm is contagious. Let people catch it today.',
      'The open road is your natural habitat. Do not let small spaces shrink you.',
      'Trust the direction you feel pulled in. The Horse rarely runs the wrong way.',
      'Spontaneity today leads to an unexpected but welcome destination.',
      'Your drive and passion are at a peak. Channel them into what matters most.',
    ],
  },
  Goat: {
    emoji: '🐐',
    tone: 'Creative, kind, peacefully abundant',
    dailyInsights: [
      'Your creativity is highest in the morning hours. Use them.',
      'Gentleness is not weakness — it is precision.',
      'The creative or artistic path today leads somewhere real.',
      'Nurture the relationship that needs your soft attention today.',
      'Beauty and calm around you directly improves your luck today.',
      'Your kindness creates ripples further than you will ever see.',
      'A creative detour today leads to the destination you actually wanted.',
      'Abundance grows in the soil of gratitude. Tend to it.',
      'Harmony in your environment translates to clarity in your thinking.',
      'Let yourself enjoy something beautiful today — it is not a distraction.',
    ],
  },
  Monkey: {
    emoji: '🐵',
    tone: 'Playful, sharp, perfectly timed',
    dailyInsights: [
      'Your timing is impeccable today. Trust your instincts over analysis.',
      'Find the humor in the situation — it unlocks the solution.',
      'Your cleverness is working in your favor. Do not overthink it.',
      'A playful approach works better than a serious one today.',
      'The opportunity today requires quick thinking. You already have it.',
      'Improvise. The script today is meant to be rewritten.',
      'Your wit is your best negotiation tool. Use it with warmth.',
      'The creative shortcut you spot today is not cheating — it is brilliance.',
      'Curiosity today leads you somewhere more interesting than the plan.',
      'Stay nimble. The best outcome today requires some mid-course adjusting.',
    ],
  },
  Rooster: {
    emoji: '🐔',
    tone: 'Polished, clear, quietly confident',
    dailyInsights: [
      'Precision matters today. Get the details exactly right.',
      'Your confidence is most attractive when it is quiet and certain.',
      'Speak clearly and directly. People respond well to your voice today.',
      'Organize one thing that has been out of order. Clarity creates luck.',
      'Your high standards are what set you apart. Hold to them.',
      'A well-prepared presentation today changes how others see you.',
      'The effort you put into your appearance and environment returns dividends.',
      'Your discernment keeps you safe in situations where others get swept away.',
      'Announce your intentions early today — timing and clarity are everything.',
      'You notice flaws others miss. That attention to quality is your edge.',
    ],
  },
  Dog: {
    emoji: '🐶',
    tone: 'Loyal, protective, deeply honest',
    dailyInsights: [
      'The person who needs you most today is someone you already trust.',
      'Your loyalty is your best quality and your best protection.',
      'Honesty today costs less than it feels like it will. Say the true thing.',
      'Stand by someone who cannot stand up for themselves right now.',
      'Your protective instincts are correct today. Trust them.',
      'The bond you invest in today grows into something unbreakable.',
      'Your consistency over time is quietly building something remarkable.',
      'A simple act of showing up for someone today means more than you know.',
      'Integrity in a small thing today sets the tone for everything that follows.',
      'You guard others well. Do not forget to extend that protection to yourself.',
    ],
  },
  Pig: {
    emoji: '🐷',
    tone: 'Warm, generous, abundantly open',
    dailyInsights: [
      'Generosity today comes back multiplied. Give without keeping score.',
      'Your warmth makes people feel safe. That is a rare and lucky gift.',
      'Abundance finds the person who is already grateful. Count yours.',
      'Enjoy the small pleasures today without rushing past them.',
      'Your open heart is your fortune. Do not close it off.',
      'A kind word from you today carries more weight than you realize.',
      'Good food, good company, and gratitude — let yourself have all three.',
      'The abundance you seek is already arriving. Create space to receive it.',
      'Your sincerity is magnetic. People trust the Pig because they feel it.',
      'Celebrate even the small wins today. Joy compounds just like luck.',
    ],
  },
};

export function getChineseZodiacDetails(animal: string) {
  return zodiacDetails[animal] ?? { emoji: '✨', tone: 'Personal luck energy', dailyInsights: ['Your energy carries unique fortune today.'] };
}

export function getChineseZodiacDailyInsight(animal: string, seed: number): string {
  const details = zodiacDetails[animal];
  if (!details) return 'Your energy carries unique fortune today.';
  return details.dailyInsights[Math.abs(seed) % details.dailyInsights.length];
}
