const westernZodiacInsights: Record<string, string[]> = {
  Aries: [
    'your boldest move today is also your strongest. Lead before you are ready.',
    'Impatience is information. What it points to is exactly where you need to go.',
    'The first instinct is the right one. Trust it before logic talks you out of it.',
    'Your energy today is contagious. Use it to start, not just to push.',
    'Conflict you have been avoiding is costing more than the conversation would.',
    'Move fast, but listen once before you act. The slight pause pays off today.',
    'Your drive today is at its peak. Aim it at the thing that matters most.',
    'Competition brings out your best. Let it sharpen you, not consume you.',
    'The door you kick open today was already unlocked. You just needed to try.',
    'Others see your confidence as permission. Give it today and watch what follows.',
    'The window for this move is open right now. You will not have more clarity by waiting.',
    'Your frustration today is just energy without a direction yet. Give it one.',
    'Leading by example is your strongest mode today. Show them instead of telling them.',
    'The plan that excites you most is probably the right one. Go with what makes you feel alive.',
    'Your directness today cuts through what subtlety would leave muddy.',
    'When you run at the obstacle instead of around it, it is usually smaller than it looked.',
    'The role of pioneer suits you. Be first today — others will follow.',
    'Risk that excites you is almost always the right kind. Analyze once, then commit.',
    'Your best ideas come in motion — move your body before you make the decision.',
    'Aries fire is at its most useful when it is focused, not scattered. Pick one thing.',
  ],
  Taurus: [
    'What you build slowly is what lasts. Do not rush the thing that is working.',
    'Your body is giving you information today. Listen to what it is asking for.',
    'The comfort you create for others is your quiet superpower. Use it.',
    'Patience today is not passivity. It is precision in choosing the right moment.',
    'Something you have been loyal to is about to reward that loyalty.',
    'Trust what you have built. The foundation holds even when it does not feel like it.',
    'A small pleasure today — good food, beautiful surroundings — restores your power.',
    'Your eye for quality catches what others miss. Let it guide a decision today.',
    'Stubbornness becomes wisdom when you are right. Make sure you are right today.',
    'The slow path is not the wrong path. You arrived at the pace that let you stay.',
    'Loyalty to your plan today beats the distraction of someone else\'s urgency.',
    'Your sense of quality finds the flaw before it becomes a problem. Trust that perception.',
    'Patience in a conversation today keeps something worth keeping intact.',
    'What you have earned through quiet effort is worth protecting today.',
    'Your persistence past the point where others quit is what makes the difference.',
    'The physical world — your home, your body, your space — deserves attention today.',
    'One thing finished completely feels better than three things half-done.',
    'Your aesthetic sense is data. When something looks wrong, it is worth investigating.',
    'Security is what you build, not what you wait for. Build one small piece today.',
    'The investment in comfort — your own or someone else\'s — returns more than you expect.',
  ],
  Gemini: [
    'Two ideas that seem opposite are both correct today. Hold the tension.',
    'Your curiosity is a compass. The subject you cannot stop reading about is your next move.',
    'You communicate something important today better than anyone else could.',
    'Change your mind if the evidence changes. Flexibility is not weakness today.',
    'The conversation you keep starting in your head needs to happen out loud.',
    'Your adaptability today is your edge. Others are frozen; you are already moving.',
    'Quick thinking plus one moment of patience produces your best result today.',
    'An idea you mentioned casually lands differently than you expected. Pay attention.',
    'You process information faster than the room. Slow down enough to bring people with you.',
    'The answer you have been looking for is in a book, a link, or a conversation. Find it.',
    'The connection between two things no one else sees is your insight for the day.',
    'Your facility with language gives you the right word at the right moment today.',
    'Boredom is your signal that you are under-challenged. Find the harder version today.',
    'Your social intelligence reads the room faster than conscious thought. Trust what you pick up.',
    'The information you gather casually today is surprisingly valuable. Pay attention.',
    'Your versatility is an asset no specialist can replicate. Apply it to today\'s problem.',
    'The twin perspective — your ability to hold two truths — resolves something today.',
    'A conversation started lightly becomes something substantive today. Stay with it.',
    'Your mind is restless because it wants more input. Feed it with something good.',
    'The parallel between two situations you have been tracking — the connection pays off today.',
  ],
  Cancer: [
    'Your intuition today is running ahead of the facts. Trust it anyway.',
    'The person you have been quietly worrying about needs to hear from you.',
    'Protect your energy today — it is higher than usual and worth guarding.',
    'Home, in whatever form that takes for you today, is where you feel renewed.',
    'Your memory for how people feel is a gift. Use it to repair something today.',
    'Vulnerability in the right moment today opens a door that nothing else could.',
    'You sense what others have not said yet. That knowing is real and accurate.',
    'Nurture yourself first today. You cannot pour from what you have not filled.',
    'Your loyalty is a form of wealth. The people you keep close are the return on it.',
    'The soft approach today produces a result that force never could have.',
    'The home you create in your relationships is where your real power lives today.',
    'Your empathy today reads beneath what people say to what they actually mean.',
    'Mood and environment are deeply linked for you. Tend to your surroundings today.',
    'Your memory of how someone felt is more accurate than their words. Trust it.',
    'The protective instinct you feel today is accurate. Act on it gently.',
    'Rest is not retreat — for you, it is the source of tomorrow\'s strength.',
    'Something you have been carrying emotionally is ready to be set down today.',
    'Your intuition about the relationship is correct. The evidence will catch up.',
    'The soft thing you needed to hear — say it to yourself first today.',
    'Caretaking you offer almost instinctively today matters more than logic would suggest.',
  ],
  Leo: [
    'The room responds to how you enter it. Enter it like you belong there.',
    'Generosity today comes back in a form bigger than what you gave.',
    'Your creativity is louder than usual. Let it make something visible today.',
    'Confidence is not arrogance when it is backed by genuine effort. Back it today.',
    'Someone today needs to see you at your best. Show up fully.',
    'The recognition you want is earned by one more act of excellence. Do it.',
    'Your warmth makes people feel chosen. Someone today needs that feeling.',
    'Drama only serves you when it is in the performance, not in the relationship.',
    'Lead with your heart today. The head will follow and refine.',
    'Your light does not take from anyone else. Shine without apology.',
    'The performance you bring to ordinary moments today is actually extraordinary.',
    'Recognition you offer someone today returns as respect for you tomorrow.',
    'Your energy is a gift to whatever room you enter. Walk in with full presence.',
    'The creative impulse you are feeling is not an indulgence. Follow it today.',
    'Pride in your work is not arrogance. Hold your head up — you have earned it.',
    'Your loyalty to the people you love is what makes your circle trust you.',
    'What you appreciate out loud today becomes more present in your life tomorrow.',
    'Leading with your heart today is not reckless — it is your particular form of wisdom.',
    'The stage is yours — not to dominate, but to illuminate something useful today.',
    'Your generosity is most powerful when it is specific. Give something particular today.',
  ],
  Virgo: [
    'The detail everyone else overlooked is the one that saves the day. You already spotted it.',
    'Your analysis today reaches a conclusion others will take weeks to reach. Trust it.',
    'Perfect is the enemy of done — but your version of done is already excellent.',
    'Organize one area of your life today. The clarity spreads outward.',
    'Service is your love language. The help you give today is quietly transformative.',
    'Your critical eye protects someone today from a mistake they could not see coming.',
    'The system you build or improve today saves more time than anything else you do.',
    'Precision in one small thing today sets the tone for everything that follows.',
    'Your discernment is the gift. It filters what others cannot. Use it wisely today.',
    'Health and routine are your anchor. Return to them if today feels unsteady.',
    'The improvement you make to a process today saves future effort in a compounding way.',
    'Your care for the details in the work is what transforms good into truly reliable.',
    'The checklist mentality today prevents the mistake everyone else is about to make.',
    'Something you dismissed as too small to address is actually worth your attention today.',
    'The flaw you notice is not criticism — it is craft. Trust your eye.',
    'Humility today creates room for collaboration that produces something better.',
    'Your work ethic today is setting the standard without announcing it.',
    'Health routines started or returned to today take hold faster than expected.',
    'The analysis you bring to a problem today is the most accurate in the room.',
    'Your attention to what is missing is what elevates ordinary work into something polished.',
  ],
  Libra: [
    'The fairest outcome today requires you to also advocate for yourself.',
    'Your charm opens doors that no amount of force could touch. Use it deliberately.',
    'Indecision is sometimes wisdom in disguise. But today, the moment is ready. Choose.',
    'A relationship you invest in today returns interest for a long time.',
    'Beauty in your environment today is not superficial — it directly improves your output.',
    'You see both sides better than anyone. Let that perspective lead the conversation.',
    'Balance is not static. It is constant small adjustments. Make one today.',
    'The diplomatic word you choose today saves something worth saving.',
    'Partnership energy is strong today. A collaboration produces more than either alone.',
    'Your sense of fairness is a rare quality. Let it guide a difficult call today.',
    'Your diplomacy today creates agreement where conflict was about to take hold.',
    'Balance in your relationships starts with balance in how you treat yourself today.',
    'Your ability to see the other perspective is rare. Offer it where it is most needed.',
    'A decision made with both head and heart today produces the outcome you want.',
    'The unfair thing you noticed is worth naming — you have the words for it today.',
    'Your sense of proportion keeps you from overdoing in either direction. Trust it.',
    'Partnership that you invest in genuinely today becomes part of what carries you forward.',
    'Harmony is not avoiding conflict. It is finding the version where both people can stay.',
    'Your taste and judgment today are your most reliable guides. Let them lead.',
    'The art you make or appreciate today is not separate from your practical day. It feeds it.',
  ],
  Scorpio: [
    'You already know the truth of the situation. Trust what you sense beneath the surface.',
    'Transformation is not comfortable. The discomfort today is the process working.',
    'Your intensity is an asset when it is focused. Narrow it today.',
    'Let one thing end. The thing you are holding onto costs more than its worth.',
    'Your perception reads what people cannot hide. Use that knowledge with care.',
    'The investigation you started — in any form — reaches its answer today.',
    'Depth over breadth. One real conversation beats ten surface-level ones.',
    'Power is not in how much you reveal. It is in how precisely you act on what you know.',
    'Your resilience is tested most just before it pays off. You are almost through.',
    'The silence you hold today communicates more than words would have.',
    'The thing being left unsaid in the room is what you have already understood.',
    'Your loyalty runs deeper than most. What you commit to today you will not abandon.',
    'Transformation is not destruction — even when it feels that way. Trust the process.',
    'The question beneath the question — you see it. Ask the real one today.',
    'Power used with restraint is more effective than power used loudly. Choose restraint.',
    'Something you released is making room for something better. That choice was correct.',
    'Your research instinct today reaches past the surface to where the real answer is.',
    'Depth of commitment today is what separates your outcomes from everyone around you.',
    'What others call stubborn, you call thorough. Today, being thorough wins.',
    'Your intensity is most useful when you direct it precisely. Pick your target today.',
  ],
  Sagittarius: [
    'The adventure you need today does not have to be far away. Find it in a new idea.',
    'Your optimism is not naïve — it is a strategy that bends probability.',
    'The truth you speak bluntly today lands better than a careful version would.',
    'Expand your thinking before you expand your plans. The bigger picture is available to you.',
    'Freedom is your fuel. Protect one part of today that belongs only to you.',
    'Your philosophy today is your compass. Return to what you actually believe.',
    'A trip, a book, a conversation — something expansive calls you today. Answer it.',
    'Your humor defuses what seriousness cannot. Use it at the right moment.',
    'The foreign, the unfamiliar, the different — that is where your day lives today.',
    'You see possibility where others see limitation. Say it out loud today.',
    'The horizon you keep your eyes on helps others believe there is one worth moving toward.',
    'Your philosophical bent today has a practical application. Find it and apply it.',
    'The adventure is in the question, not just the answer. Sit with it longer today.',
    'Your faith in positive outcomes actually influences the probability of them.',
    'The restless feeling is not dissatisfaction — it is preparation. Something is coming.',
    'Big-picture thinking today gives you an advantage in the small decisions.',
    'Honesty offered with generosity today is received completely differently than usual.',
    'The meaning you bring to what you do makes you unusually effective today.',
    'Risk calibrated with wisdom is not recklessness. You already know the difference.',
    'Your expansive nature is most powerful when it is also grounded. Find both today.',
  ],
  Capricorn: [
    'The work you put in quietly today is the investment that compounds the longest.',
    'Your ambition today is not selfishness. It is discipline applied to a worthy target.',
    'Status is earned not declared. One visible act of excellence today advances both.',
    'The long game you are playing is the right one. Do not let short-term noise distract you.',
    'Structure is your sanctuary. Build or restore one today and feel the difference.',
    'Practical action beats perfect planning. Move one thing from planning to doing today.',
    'Your reputation is an asset that grows through consistent action. Add to it today.',
    'The summit looks far but today\'s step is the only one that matters. Take it.',
    'Responsibility handled well today earns you freedom later. Do not cut corners.',
    'Your patience in this process is not wasted time. It is architecture.',
    'The investment you make in your discipline today pays the largest dividend later.',
    'Your sense of duty today produces something that ambition alone never could.',
    'Efficiency in one part of your day frees the energy the important part actually needs.',
    'Something you have been building is closer to viable than it looks right now. Continue.',
    'Your instinct to finish before you celebrate — correct. The celebration will be fuller.',
    'Authority earned through competence is the only kind worth having. Add to it today.',
    'What you sacrifice for excellence today returns as reputation that opens future doors.',
    'Your patience is not waiting — it is deliberate positioning. You are in the right place.',
    'The mountain does not shrink. You just become more capable with every step you take.',
    'Practical matters handled well today become the foundation your ambition stands on.',
  ],
  Aquarius: [
    'The unconventional idea you dismissed is the one worth revisiting today.',
    'Your independence is not isolation — it is the space that produces original thinking.',
    'The future you envision is more possible today than it was yesterday. Act on it.',
    'Connection with people who think differently from you is where your growth is today.',
    'Your detachment today allows you to see clearly what others are too close to see.',
    'The system that frustrates you is the one you are meant to change. Start today.',
    'Innovation does not require permission. Move forward on the idea without waiting.',
    'Your humanitarian instinct points at something worth doing today. Follow it.',
    'Originality is your natural state. Do not perform convention today.',
    'The group you contribute to today benefits more than you will see immediately.',
    'The future you are building is worth the strangeness of explaining it to people in the present.',
    'Your vision today sees past the convention that is confining everyone around you.',
    'The thing no one has tried yet is waiting for someone exactly like you to attempt it.',
    'Community built on shared values is stronger than any built on shared history.',
    'Your perspective from outside the group is exactly the angle the group needs today.',
    'Ideas that feel ahead of their time are usually just early. Stay with this one.',
    'Rational detachment today lets you see what emotion is making everyone else miss.',
    'The collaboration between very different thinkers produces something neither could alone.',
    'Your humanitarianism today is not abstract. Find its specific, concrete expression.',
    'The unconventional path is not the longer one. For you, it is usually the shorter one.',
  ],
  Pisces: [
    'Your empathy today reads the room before a word is spoken. Trust that reading.',
    'The dream you had — literally or figuratively — contains real information. Sit with it.',
    'Creative work done today flows in a way it rarely does. Do not interrupt it.',
    'Your compassion is not weakness. It is a form of intelligence that logic cannot reach.',
    'The boundary you set today protects not just you but the relationship.',
    'Intuition and imagination together are your most accurate instruments today.',
    'Something you feel before you can explain it is pointing you in the right direction.',
    'Let yourself dissolve into the work, the music, or the moment. That is where your day is.',
    'Healing — your own or someone else\'s — is available today. Open to it.',
    'The spiritual dimension of today is more real than the practical. Lead with it.',
    'The dream logic today applies to a real decision. Follow it where it leads.',
    'Your compassion for others is most powerful when you first extend it inward.',
    'The creative flow that wants to move through you today is looking for a door. Open one.',
    'Empathy is a skill, not just a feeling. Yours is operating at its highest right now.',
    'Your sensitivity to the unseen is accurate today. Name what you feel before it fades.',
    'What you visualize with genuine feeling today carries more influence than you expect.',
    'The art, the music, the beauty — they are not distractions. They are today\'s fuel.',
    'Your faith in what you cannot yet see is a form of intelligence logic cannot reach.',
    'Healing is available today — for you or through you. Accept it or offer it.',
    'The invisible current in the room today is visible to you. Follow where it points.',
  ],
};

export function getWesternZodiacDailyInsight(sign: string, seed: number): string {
  const insights = westernZodiacInsights[sign];
  if (!insights || insights.length === 0) return '';
  return insights[Math.abs(seed) % insights.length];
}
