const westernZodiacInsights: Record<string, string[]> = {
  Aries: [
    'Your boldest move today is also your luckiest. Lead before you are ready.',
    'Impatience is information. What it points to is exactly where you need to go.',
    'The first instinct is the right one. Trust it before logic talks you out of it.',
    'Your energy today is contagious. Use it to start, not just to push.',
    'Conflict you have been avoiding is costing more than the conversation would.',
    'Move fast, but listen once before you act. The slight pause pays off today.',
    'Your drive today is at its peak. Aim it at the thing that matters most.',
    'Competition brings out your best. Let it sharpen you, not consume you.',
    'The door you kick open today was already unlocked. You just needed to try.',
    'Others see your confidence as permission. Give it today and watch what follows.',
  ],
  Taurus: [
    'What you build slowly is what lasts. Do not rush the thing that is working.',
    'Your body is giving you information today. Listen to what it is asking for.',
    'The comfort you create for others is your quiet superpower. Use it.',
    'Patience today is not passivity. It is precision in choosing the right moment.',
    'Something you have been loyal to is about to reward that loyalty.',
    'Trust what you have built. The foundation holds even when it does not feel like it.',
    'A small pleasure today — good food, beautiful surroundings — restores your power.',
    'Your eye for quality catches what others miss. Let it guide a decision today.',
    'Stubbornness becomes wisdom when you are right. Make sure you are right today.',
    'The slow path is not the wrong path. You arrived at the pace that let you stay.',
  ],
  Gemini: [
    'Two ideas that seem opposite are both correct today. Hold the tension.',
    'Your curiosity is a compass. The subject you cannot stop reading about is your next move.',
    'You communicate something important today better than anyone else could.',
    'Change your mind if the evidence changes. Flexibility is not weakness today.',
    'The conversation you keep starting in your head needs to happen out loud.',
    'Your adaptability today is your edge. Others are frozen; you are already moving.',
    'Quick thinking plus one moment of patience produces your best result today.',
    'An idea you mentioned casually lands differently than you expected. Pay attention.',
    'You process information faster than the room. Slow down enough to bring people with you.',
    'The answer you have been looking for is in a book, a link, or a conversation. Find it.',
  ],
  Cancer: [
    'Your intuition today is running ahead of the facts. Trust it anyway.',
    'The person you have been quietly worrying about needs to hear from you.',
    'Protect your energy today — it is higher than usual and worth guarding.',
    'Home, in whatever form that takes for you today, is where your luck is renewed.',
    'Your memory for how people feel is a gift. Use it to repair something today.',
    'Vulnerability in the right moment today opens a door that nothing else could.',
    'You sense what others have not said yet. That knowing is real and accurate.',
    'Nurture yourself first today. You cannot pour from what you have not filled.',
    'Your loyalty is a form of wealth. The people you keep close are the return on it.',
    'The soft approach today produces a result that force never could have.',
  ],
  Leo: [
    'The room responds to how you enter it. Enter it like you belong there.',
    'Generosity today comes back in a form bigger than what you gave.',
    'Your creativity is louder than usual. Let it make something visible today.',
    'Confidence is not arrogance when it is backed by genuine effort. Back it today.',
    'Someone today needs to see you at your best. Show up fully.',
    'The recognition you want is earned by one more act of excellence. Do it.',
    'Your warmth makes people feel chosen. Someone today needs that feeling.',
    'Drama only serves you when it is in the performance, not in the relationship.',
    'Lead with your heart today. The head will follow and refine.',
    'Your light does not take from anyone else. Shine without apology.',
  ],
  Virgo: [
    'The detail everyone else overlooked is the one that saves the day. You already spotted it.',
    'Your analysis today reaches a conclusion others will take weeks to reach. Trust it.',
    'Perfect is the enemy of done — but your version of done is already excellent.',
    'Organize one area of your life today. The clarity spreads outward.',
    'Service is your love language. The help you give today is quietly transformative.',
    'Your critical eye protects someone today from a mistake they could not see coming.',
    'The system you build or improve today saves more time than anything else you do.',
    'Precision in one small thing today sets the tone for everything that follows.',
    'Your discernment is the gift. It filters what others cannot. Use it wisely today.',
    'Health and routine are your anchor. Return to them if today feels unsteady.',
  ],
  Libra: [
    'The fairest outcome today requires you to also advocate for yourself.',
    'Your charm opens doors that no amount of force could touch. Use it deliberately.',
    'Indecision is sometimes wisdom in disguise. But today, the moment is ready. Choose.',
    'A relationship you invest in today returns interest for a long time.',
    'Beauty in your environment today is not superficial — it directly improves your output.',
    'You see both sides better than anyone. Let that perspective lead the conversation.',
    'Balance is not static. It is constant small adjustments. Make one today.',
    'The diplomatic word you choose today saves something worth saving.',
    'Partnership energy is strong today. A collaboration produces more than either alone.',
    'Your sense of fairness is a rare quality. Let it guide a difficult call today.',
  ],
  Scorpio: [
    'You already know the truth of the situation. Trust what you sense beneath the surface.',
    'Transformation is not comfortable. The discomfort today is the process working.',
    'Your intensity is an asset when it is focused. Narrow it today.',
    'Let one thing end. The thing you are holding onto costs more than its worth.',
    'Your perception reads what people cannot hide. Use that knowledge with care.',
    'The investigation you started — in any form — reaches its answer today.',
    'Depth over breadth. One real conversation beats ten surface-level ones.',
    'Power is not in how much you reveal. It is in how precisely you act on what you know.',
    'Your resilience is tested most just before it pays off. You are almost through.',
    'The silence you hold today communicates more than words would have.',
  ],
  Sagittarius: [
    'The adventure you need today does not have to be far away. Find it in a new idea.',
    'Your optimism is not naïve — it is a strategy that bends probability.',
    'The truth you speak bluntly today lands better than a careful version would.',
    'Expand your thinking before you expand your plans. The bigger picture is available to you.',
    'Freedom is your fuel. Protect one part of today that belongs only to you.',
    'Your philosophy today is your compass. Return to what you actually believe.',
    'A trip, a book, a conversation — something expansive calls you today. Answer it.',
    'Your humor defuses what seriousness cannot. Use it at the right moment.',
    'The foreign, the unfamiliar, the different — that is where your luck lives today.',
    'You see possibility where others see limitation. Say it out loud today.',
  ],
  Capricorn: [
    'The work you put in quietly today is the investment that compounds the longest.',
    'Your ambition today is not selfishness. It is discipline applied to a worthy target.',
    'Status is earned not declared. One visible act of excellence today advances both.',
    'The long game you are playing is the right one. Do not let short-term noise distract you.',
    'Structure is your sanctuary. Build or restore one today and feel the difference.',
    'Practical action beats perfect planning. Move one thing from planning to doing today.',
    'Your reputation is an asset that grows through consistent action. Add to it today.',
    'The summit looks far but today\'s step is the only one that matters. Take it.',
    'Responsibility handled well today earns you freedom later. Do not cut corners.',
    'Your patience in this process is not wasted time. It is architecture.',
  ],
  Aquarius: [
    'The unconventional idea you dismissed is the one worth revisiting today.',
    'Your independence is not isolation — it is the space that produces original thinking.',
    'The future you envision is more possible today than it was yesterday. Act on it.',
    'Connection with people who think differently from you is where your growth is today.',
    'Your detachment today allows you to see clearly what others are too close to see.',
    'The system that frustrates you is the one you are meant to change. Start today.',
    'Innovation does not require permission. Move forward on the idea without waiting.',
    'Your humanitarian instinct points at something worth doing today. Follow it.',
    'Originality is your natural state. Do not perform convention today.',
    'The group you contribute to today benefits more than you will see immediately.',
  ],
  Pisces: [
    'Your empathy today reads the room before a word is spoken. Trust that reading.',
    'The dream you had — literally or figuratively — contains real information. Sit with it.',
    'Creative work done today flows in a way it rarely does. Do not interrupt it.',
    'Your compassion is not weakness. It is a form of intelligence that logic cannot reach.',
    'The boundary you set today protects not just you but the relationship.',
    'Intuition and imagination together are your most accurate instruments today.',
    'Something you feel before you can explain it is pointing you in the right direction.',
    'Let yourself dissolve into the work, the music, or the moment. That is where your luck is.',
    'Healing — your own or someone else\'s — is available today. Open to it.',
    'The spiritual dimension of today is more real than the practical. Lead with it.',
  ],
};

export function getWesternZodiacDailyInsight(sign: string, seed: number): string {
  const insights = westernZodiacInsights[sign];
  if (!insights || insights.length === 0) return '';
  return insights[Math.abs(seed) % insights.length];
}
