#!/bin/bash
# LuckyDay daily-log routine.
#
# Appends a single dated journal entry to docs/daily-log.md summarising the
# day's automated work (commits + key artifact changes). Commits and pushes
# to whatever branch is currently checked out — does NOT switch branches.
#
# Schedules via launchd (~/Library/LaunchAgents/com.luckyday.daily-log.plist).
# Run manually for a smoke test:
#   bash scripts/daily-log.sh
#
# Safety:
#   - Exits non-zero on any git failure so launchd can report it
#   - Skips push if no new content was added (won't churn)
#   - Never force-pushes, never switches branches, never edits other files
set -euo pipefail

REPO_DIR="/Users/santipapmay/Downloads/LuckyDay"
LOG_FILE="$REPO_DIR/docs/daily-log.md"
RUN_LOG="$REPO_DIR/scripts/.daily-log.last-run.log"

cd "$REPO_DIR"

DATE_HEADER="$(date '+%Y-%m-%d')"
TIME_STAMP="$(date '+%H:%M %Z')"

# Bootstrap the file if it doesn't exist.
if [ ! -f "$LOG_FILE" ]; then
  cat > "$LOG_FILE" <<HEADER
# LuckyDay — Daily Log

One dated journal entry per day generated by scripts/daily-log.sh.
Captures commit activity + key artifact churn so the GitHub contribution
graph reflects the work the routines are actually doing.

HEADER
fi

# Don't add a duplicate entry if today's heading is already present.
if grep -q "^## $DATE_HEADER\b" "$LOG_FILE"; then
  echo "[daily-log] Entry for $DATE_HEADER already exists — skipping append." | tee "$RUN_LOG"
  exit 0
fi

# Gather a tiny activity summary for today.
BRANCH="$(git rev-parse --abbrev-ref HEAD)"
COMMITS_TODAY="$(git log --since="$DATE_HEADER 00:00" --pretty=format:'- %h %s' || true)"
SCREENSHOT_DIR_TODAY="docs/screenshots/$DATE_HEADER"
READING_AUDIT_TODAY="docs/reading-audits/$DATE_HEADER.md"
DELIGHT_TODAY="docs/delight-audit/$DATE_HEADER.md"
COMPETITOR_TODAY="$(ls docs/competitor-insights/$DATE_HEADER-*.md 2>/dev/null || true)"

ARTIFACTS=""
[ -d "$SCREENSHOT_DIR_TODAY" ] && ARTIFACTS+="- Screenshots captured in \`$SCREENSHOT_DIR_TODAY/\`\n"
[ -f "$READING_AUDIT_TODAY" ] && ARTIFACTS+="- Reading-soul audit: \`$READING_AUDIT_TODAY\`\n"
[ -f "$DELIGHT_TODAY" ] && ARTIFACTS+="- Delight audit: \`$DELIGHT_TODAY\`\n"
[ -n "$COMPETITOR_TODAY" ] && ARTIFACTS+="- Competitor mining: \`$COMPETITOR_TODAY\`\n"

if [ -z "$COMMITS_TODAY" ] && [ -z "$ARTIFACTS" ]; then
  COMMITS_TODAY="- (no automated commits today — Codex routines may have been paused)"
fi

# Append the new entry.
{
  echo ""
  echo "## $DATE_HEADER"
  echo ""
  echo "_Logged at $TIME_STAMP on branch \`$BRANCH\`._"
  echo ""
  echo "**Commits today:**"
  echo ""
  if [ -n "$COMMITS_TODAY" ]; then
    echo "$COMMITS_TODAY"
  fi
  if [ -n "$ARTIFACTS" ]; then
    echo ""
    echo "**Artifacts touched:**"
    echo ""
    printf '%b' "$ARTIFACTS"
  fi
} >> "$LOG_FILE"

# Commit + push. Use a low-noise conventional commit message.
git add "$LOG_FILE"
if git diff --cached --quiet; then
  echo "[daily-log] Nothing staged after append (unexpected) — skipping commit." | tee "$RUN_LOG"
  exit 0
fi

git commit -m "docs: daily-log entry $DATE_HEADER" --no-verify
git push origin "$BRANCH" 2>&1 | tee "$RUN_LOG"

echo "[daily-log] Pushed daily-log entry for $DATE_HEADER on branch $BRANCH." | tee -a "$RUN_LOG"
